#!/bin/sh

# Copyright (c) 2011 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

. /etc/he.conf
if ! ftp -o /var/log/ipv4update.log \
	"https://ipv4.tunnelbroker.net/ipv4_end.php?ipv4b=AUTO&pass=$MD5PASS&user_id=$USERID&tunnel_id=$GTUNID"; then
	echo "Failed to update he.net IPv6 tunnel"
fi

localip=$(ifconfig egress | awk '$1 ~ /^inet$/{print $2}')
#
#        tunnel: inet 1.2.3.4 -> 1.6.2.2

rmtip=$(ifconfig egress | awk '/tunnel: inet /{print $5}')
if [ "$localip" -a "$rmtip" ]; then
	/sbin/ifconfig gif0 tunnel $localip $rmtip
else
	echo "gif0 localip=$localip rmtip=$rmtip"
fi
