#!/bin/sh

# Copyright (c) 2011 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

URL="https://ipv4.tunnelbroker.net/ipv4_end.php?ipv4b=%4%&pass=%P%&user_id=%U%&tunnel_id=%T%"
URL="https://ipv4.tunnelbroker.net/ipv4_end.php?ipv4b=%4%&pass=%P%&user_id=%U%&tunnelid=%T%"
URL="https://ipv4.tunnelbroker.net/ipv4_end.php?ipv4b=%4%&password=%P%&username=%U%&tunnel_id=%T%"
URL="https://%U%:%P%@ipv4.tunnelbroker.net/ipv4_end.php?ip=%4%&tid=%T%&update=Submit"
URL="https://%N%:%O%@ipv4.tunnelbroker.net/ipv4_end.php?ip=%4%&tid=%T%"
URL="https://%Q%:%O%@ipv4.tunnelbroker.net/ipv4_end.php?ip=%4%&tid=%T%"
URL="http://ipv4.tunnelbroker.net/ipv4_end.php?ip=%4%&pass=%P%&user_id=%Q%&tid=%T%"
. /etc/he.conf

LOCIP=$(ifconfig egress | awk '$1 ~ /^inet$/{print $2}')
URL=$(echo "$URL" | sed \
	-e "s/%P%/${MD5PASS}/g" \
	-e "s/%U%/${MD5USER}/g" \
	-e "s/%N%/${USERID}/g" \
	-e "s/%Q%/${USERNAME}/g" \
	-e "s/%O%/${PASSWORD}/g" \
	-e "s/%4%/${LOCIP}/g" \
	-e "s/%T%/${GTUNID}/g")
echo "URL=$URL"

if ! ftp -o /var/log/ipv4update.log "$URL"; then
	echo "Failed to update he.net IPv6 tunnel"
fi

#
#        tunnel: inet 1.2.3.4 -> 1.6.2.2

RMTIP=$(ifconfig egress | awk '/tunnel: inet /{print $5}')
if [ "$LOCIP" -a "$RMTIP" ]; then
	/sbin/ifconfig gif0 tunnel $LOCIP $RMTIP
else
	echo "gif0 LOCIP=$LOCIP RMTIP=$RMTIP"
fi
